version: '3'

services:
  web:
    build: 
        context: ../.
        dockerfile: '.docker/nginx/Dockerfile'
    volumes:
        - ../code:/code
        - ../.docker/nginx/:/etc/nginx/conf.d/
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"

  php:
    build: 
        context: ../.
        dockerfile: '.docker/php-fpm/Dockerfile'
    volumes:
        - ../code:/code

  workspace:
    build:
        context: ../.
        dockerfile: '.docker/workspace/Dockerfile'
    volumes:
        - ../code:/code
    ports:
      - "${WORKSPACE_HOST_SSH_PORT}:22"

